// Code generated by world sdk generate. DO NOT EDIT.

package event

import (
	pkg_cardinal "github.com/argus-labs/world-engine/pkg/cardinal"
	event "github.com/argus-labs/world-engine/pkg/plugin/physics2d/gen/pkg/plugin/physics2d/event"
	"google.golang.org/protobuf/proto"
)

func (c ContactBeginEvent) ToProto() *event.ContactBeginEvent {
	p := &event.ContactBeginEvent{}
	p.ContactEventPayload = c.ContactEventPayload.ToProto()
	return p
}

func (c ContactBeginEvent) FromProto(p *event.ContactBeginEvent) ContactBeginEvent {
	if p == nil {
		return c
	}
	c.ContactEventPayload = c.ContactEventPayload.FromProto(p.ContactEventPayload)
	return c
}

func (c ContactBeginEvent) MarshalWire() ([]byte, error) {
	return proto.Marshal(c.ToProto())
}

func (c ContactBeginEvent) UnmarshalWire(data []byte) (any, error) {
	var p event.ContactBeginEvent
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c ContactEndEvent) ToProto() *event.ContactEndEvent {
	p := &event.ContactEndEvent{}
	p.ContactEventPayload = c.ContactEventPayload.ToProto()
	return p
}

func (c ContactEndEvent) FromProto(p *event.ContactEndEvent) ContactEndEvent {
	if p == nil {
		return c
	}
	c.ContactEventPayload = c.ContactEventPayload.FromProto(p.ContactEventPayload)
	return c
}

func (c ContactEndEvent) MarshalWire() ([]byte, error) {
	return proto.Marshal(c.ToProto())
}

func (c ContactEndEvent) UnmarshalWire(data []byte) (any, error) {
	var p event.ContactEndEvent
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c ContactEventPayload) ToProto() *event.ContactEventPayload {
	p := &event.ContactEventPayload{}
	p.FilterA = c.FilterA.ToProto()
	p.FilterB = c.FilterB.ToProto()
	p.EntityA = uint32(c.EntityA)
	p.EntityB = uint32(c.EntityB)
	p.ShapeIndexA = int64(c.ShapeIndexA)
	p.ShapeIndexB = int64(c.ShapeIndexB)
	p.Normal = c.Normal.ToProto()
	p.NormalValid = bool(c.NormalValid)
	p.Point = c.Point.ToProto()
	p.PointValid = bool(c.PointValid)
	return p
}

func (c ContactEventPayload) FromProto(p *event.ContactEventPayload) ContactEventPayload {
	if p == nil {
		return c
	}
	c.FilterA = c.FilterA.FromProto(p.FilterA)
	c.FilterB = c.FilterB.FromProto(p.FilterB)
	c.EntityA = pkg_cardinal.EntityID(p.EntityA)
	c.EntityB = pkg_cardinal.EntityID(p.EntityB)
	c.ShapeIndexA = int(p.ShapeIndexA)
	c.ShapeIndexB = int(p.ShapeIndexB)
	c.Normal = c.Normal.FromProto(p.Normal)
	c.NormalValid = bool(p.NormalValid)
	c.Point = c.Point.FromProto(p.Point)
	c.PointValid = bool(p.PointValid)
	return c
}

func (c FixtureFilterBits) ToProto() *event.FixtureFilterBits {
	p := &event.FixtureFilterBits{}
	p.CategoryBits = uint64(c.CategoryBits)
	p.MaskBits = uint64(c.MaskBits)
	p.GroupIndex = int32(c.GroupIndex)
	return p
}

func (c FixtureFilterBits) FromProto(p *event.FixtureFilterBits) FixtureFilterBits {
	if p == nil {
		return c
	}
	c.CategoryBits = uint64(p.CategoryBits)
	c.MaskBits = uint64(p.MaskBits)
	c.GroupIndex = int32(p.GroupIndex)
	return c
}

func (c TriggerBeginEvent) ToProto() *event.TriggerBeginEvent {
	p := &event.TriggerBeginEvent{}
	p.ContactEventPayload = c.ContactEventPayload.ToProto()
	return p
}

func (c TriggerBeginEvent) FromProto(p *event.TriggerBeginEvent) TriggerBeginEvent {
	if p == nil {
		return c
	}
	c.ContactEventPayload = c.ContactEventPayload.FromProto(p.ContactEventPayload)
	return c
}

func (c TriggerBeginEvent) MarshalWire() ([]byte, error) {
	return proto.Marshal(c.ToProto())
}

func (c TriggerBeginEvent) UnmarshalWire(data []byte) (any, error) {
	var p event.TriggerBeginEvent
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c TriggerEndEvent) ToProto() *event.TriggerEndEvent {
	p := &event.TriggerEndEvent{}
	p.ContactEventPayload = c.ContactEventPayload.ToProto()
	return p
}

func (c TriggerEndEvent) FromProto(p *event.TriggerEndEvent) TriggerEndEvent {
	if p == nil {
		return c
	}
	c.ContactEventPayload = c.ContactEventPayload.FromProto(p.ContactEventPayload)
	return c
}

func (c TriggerEndEvent) MarshalWire() ([]byte, error) {
	return proto.Marshal(c.ToProto())
}

func (c TriggerEndEvent) UnmarshalWire(data []byte) (any, error) {
	var p event.TriggerEndEvent
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}
