# example of values needed to setup the rollup application

[app_cfg]
genesis="example_genesis.json"
grpc-only=false
home="argus"
min-gas-prices="1stake"
trace=false

[server_cfg]
minimum-gas-prices="1stake"
pruning="nothing"
inter-block-cache=false

[rollup_cfg]
aggregator=false
da_layer="celestia"
da_config='{"base_url":"http://localhost:54000","timeout":60000000000,"fee":6000,"gas_limit":6000000}' # probablybetter off set in env vars
light=false
da_block_time="6s"
block_time="10s"
namespace_id=3210 # random namespace, doesnt really matter
fraud_proofs=true
