version: '3'
services:
  cockroachdb:
    # Only use cockroachdb single-node clusters for non-production environment
    image: cockroachdb/cockroach:latest-v23.1
    command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/,size=20%
    restart: "no"
    environment:
      - COCKROACH_DATABASE=nakama
      - COCKROACH_USER=root
      - COCKROACH_PASSWORD=${DB_PASSWORD:-development}
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health?ready=1" ]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - world-engine

  nakama:
    container_name: relay_nakama
    platform: linux/amd64
    build: ./relay/nakama
    depends_on:
      cockroachdb:
        condition: service_healthy
      game_benchmark:
        condition: service_started
    environment:
      - CARDINAL_ADDR=game_benchmark:4040
      - ENABLE_DEBUG=TRUE
      - CARDINAL_NAMESPACE=testgame
      - ENABLE_ALLOWLIST=${ENABLE_ALLOWLIST:-false}
      - DB_PASSWORD=${DB_PASSWORD:-development}
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address root:$DB_PASSWORD@cockroachdb:26257/nakama &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address root:$DB_PASSWORD@cockroachdb:26257/nakama
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: [ "CMD", "/nakama/nakama", "healthcheck" ]
      interval: 20s
      timeout: 10s
      retries: 5
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped
    networks:
      - world-engine

  chain:
    container_name: evm_base_shard
    environment:
      ## Env vars reference: https://github.com/Argus-Labs/world-engine/blob/main/evm/README.md
      ## Get AUTH_TOKEN from celestia_devnet container: `$(docker exec $(docker ps -q) celestia bridge auth admin --node.store /home/celestia/bridge`
      - DA_AUTH_TOKEN=${DA_AUTH_TOKEN:-}
      - FAUCET_ADDR=${FAUCET_ADDR:-world142fg37yzx04cslgeflezzh83wa4xlmjpms0sg5}
      - BASE_SHARD_ROUTER_KEY=${BASE_SHARD_ROUTER_KEY:-abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ01}
    build:
      context: evm
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "1317"
      - "26657"
      - "9090"
      - "9601"
    ports:
      - "1317:1317"
      - "26657:26657"
      - "9090:9090"
      - "9601:9601"
      - "8545:8545"
    networks:
      - world-engine
    depends_on:
      - celestia-devnet

  celestia-devnet:
    container_name: celestia_devnet
    image: ghcr.io/rollkit/local-celestia-devnet:v0.12.1
    networks:
      - world-engine
    restart: on-failure
    ports:
      - "26657"
      - "26658:26658"
      - "26659:26659"
      - "9090"

  game_benchmark:
    container_name: test_benchmark_game
    environment:
      - CARDINAL_NAMESPACE=${CARDINAL_NAMESPACE:-testgame}
      - CARDINAL_ROLLUP_ENABLED=${CARDINAL_ROLLUP_ENABLED:-false}
      - CARDINAL_LOG_LEVEL=${CARDINAL_LOG_LEVEL:-info}
      - CARDINAL_LOG_PRETTY=${CARDINAL_LOG_PRETTY:-false}
      - REDIS_ADDRESS=${REDIS_ADDRESS:-redis:6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BASE_SHARD_SEQUENCER_ADDRESS=${BASE_SHARD_SEQUENCER_ADDRESS:-chain:9601}
      - BASE_SHARD_ROUTER_KEY=${BASE_SHARD_ROUTER_KEY:-abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ01}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}
      - TELEMETRY_STATSD_ADDRESS=${TELEMETRY_STATSD_ADDRESS}
      - TELEMETRY_TRACE_ADDRESS=${TELEMETRY_TRACE_ADDRESS}
    build:
      context: ./
      dockerfile: e2e/testgames/gamebenchmark/Dockerfile
    restart: unless-stopped
    expose:
      - "4040"
    ports:
      - "4040:4040"
      - "9020:9020"
    depends_on:
      - redis
    networks:
      - world-engine
    volumes:
      - ./profiles:/profiles

  redis:
    image: redis:latest
    command: redis-server --save ""
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - world-engine
    restart: always

  test_nakama_benchmark:
    container_name: test_nakama_benchmark
    build:
      context: ./e2e/tests/
      dockerfile: bench/Dockerfile
    depends_on:
      nakama:
        condition: service_healthy
    environment:
      - NAKAMA_ADDRESS=http://nakama:7350
    networks:
      - world-engine

volumes:
  data:
  profiles:

networks:
  world-engine:
    driver: bridge
