version: '3'
services:
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    expose:
      - "8080"
      - "5432"
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "nakama" ]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - world-engine

  nakama:
    container_name: test_nakama
    platform: linux/amd64
    build: ./e2e/tester/nakama
    depends_on:
      - postgres
      - game
    environment:
      - CARDINAL_ADDR=http://game:4040
      - CARDINAL_NAMESPACE=TESTGAME
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
    links:
      - "postgres:db"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped
    networks:
      - world-engine

  chain:
    container_name: evm_base_shard
    environment:
      ## Env vars reference: https://github.com/Argus-Labs/world-engine/blob/main/chain/README.md
      ## Get AUTH_TOKEN from celestia_devnet container: `docker logs celestia_devnet 2>&1 | grep CELESTIA_NODE_AUTH_TOKEN -A 5 | tail -n 1`
      - DA_AUTH_TOKEN=${DA_AUTH_TOKEN:-}
    build:
      context: chain
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "1317"
      - "26657"
      - "9090"
      - "9601"
    ports:
      - "1317:1317"
      - "26657:26657"
      - "9090:9090"
      - "9601:9601"
    networks:
      - world-engine
    depends_on:
      - celestia-devnet

  celestia-devnet:
    container_name: celestia_devnet
    image: ghcr.io/rollkit/local-celestia-devnet:v0.11.0-rc8
    networks:
      - world-engine
    restart: on-failure
    ports:
      - "26657"
      - "26658"
      - "26659"
      - "9090"

  game:
    container_name: test_game
    environment:
      - REDIS_ADDR=redis:6379
      - NAMESPACE=TESTGAME
      - SHARD_SEQUENCER_ADDR=chain:9601
      - BASE_SHARD_ADDR=chain:9090
    build:
      context: e2e/tester/cardinal
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4040:4040"
      - "3333:3333"
    depends_on:
      - redis
    networks:
      - world-engine

  redis:
    image: redis:latest
    command: redis-server
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - world-engine
    restart: always

volumes:
  data:

networks:
  world-engine:
    driver: bridge
