package internal

import "fmt"

func AReallyLongFunction() {
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
	fmt.Println("This function has a lot of lines")
}

func ANotSoLongFunction() {
	fmt.Println("This function doesn't have so many lines")
	fmt.Println("This function doesn't have so many lines")
	fmt.Println("This function doesn't have so many lines")
	fmt.Println("This function doesn't have so many lines")
	fmt.Println("This function doesn't have so many lines")
}
