apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cardinal-operator
  name: controller-manager
  namespace: cardinal-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cardinal-operator
  name: leader-election-role
  namespace: cardinal-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - cardinal.argus.gg
  resources:
  - shardpools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cardinal.argus.gg
  resources:
  - shardpools/finalizers
  verbs:
  - update
- apiGroups:
  - cardinal.argus.gg
  resources:
  - shardpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - networking.gke.io
  resources:
  - gcpbackendpolicies
  - healthcheckpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - traefik.io
  resources:
  - middlewares
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cardinal-operator
  name: shardpool-admin-role
rules:
- apiGroups:
  - cardinal.argus.gg
  resources:
  - shardpools
  verbs:
  - '*'
- apiGroups:
  - cardinal.argus.gg
  resources:
  - shardpools/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cardinal-operator
  name: shardpool-editor-role
rules:
- apiGroups:
  - cardinal.argus.gg
  resources:
  - shardpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cardinal.argus.gg
  resources:
  - shardpools/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cardinal-operator
  name: shardpool-viewer-role
rules:
- apiGroups:
  - cardinal.argus.gg
  resources:
  - shardpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cardinal.argus.gg
  resources:
  - shardpools/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cardinal-operator
  name: leader-election-rolebinding
  namespace: cardinal-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: cardinal-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cardinal-operator
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: cardinal-operator-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cardinal-operator
    control-plane: controller-manager
  name: cardinal-operator
  namespace: cardinal-operator-system
spec:
  ports:
  - name: api
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app.kubernetes.io/name: cardinal-operator
    control-plane: controller-manager
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cardinal-operator
    control-plane: controller-manager
  name: controller-manager
  namespace: cardinal-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cardinal-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: cardinal-operator
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        command:
        - /ko-app/cmd
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_REGION
          value: local
        - name: AUTH_MODE
          value: PASSTHROUGH
        - name: SHARD_AUTH_MODE
          value: DEV
        - name: NATS_URL
          value: nats://nats.nats.svc.cluster.local:4222
        image: us-west1-docker.pkg.dev/argus-gg-dev/public-containers/apps/cardinal-operator:v0.10.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports: []
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts: []
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes: []
