// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIAPFacebookInstantConfig is an autogenerated mock type for the IAPFacebookInstantConfig type
type MockIAPFacebookInstantConfig struct {
	mock.Mock
}

type MockIAPFacebookInstantConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAPFacebookInstantConfig) EXPECT() *MockIAPFacebookInstantConfig_Expecter {
	return &MockIAPFacebookInstantConfig_Expecter{mock: &_m.Mock}
}

// GetAppSecret provides a mock function with no fields
func (_m *MockIAPFacebookInstantConfig) GetAppSecret() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppSecret")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIAPFacebookInstantConfig_GetAppSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppSecret'
type MockIAPFacebookInstantConfig_GetAppSecret_Call struct {
	*mock.Call
}

// GetAppSecret is a helper method to define mock.On call
func (_e *MockIAPFacebookInstantConfig_Expecter) GetAppSecret() *MockIAPFacebookInstantConfig_GetAppSecret_Call {
	return &MockIAPFacebookInstantConfig_GetAppSecret_Call{Call: _e.mock.On("GetAppSecret")}
}

func (_c *MockIAPFacebookInstantConfig_GetAppSecret_Call) Run(run func()) *MockIAPFacebookInstantConfig_GetAppSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIAPFacebookInstantConfig_GetAppSecret_Call) Return(_a0 string) *MockIAPFacebookInstantConfig_GetAppSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAPFacebookInstantConfig_GetAppSecret_Call) RunAndReturn(run func() string) *MockIAPFacebookInstantConfig_GetAppSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAPFacebookInstantConfig creates a new instance of MockIAPFacebookInstantConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAPFacebookInstantConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAPFacebookInstantConfig {
	mock := &MockIAPFacebookInstantConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
