// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	runtime "github.com/heroiclabs/nakama-common/runtime"
	mock "github.com/stretchr/testify/mock"
)

// MockFleetManager is an autogenerated mock type for the FleetManager type
type MockFleetManager struct {
	mock.Mock
}

type MockFleetManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFleetManager) EXPECT() *MockFleetManager_Expecter {
	return &MockFleetManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, maxPlayers, userIds, latencies, metadata, callback
func (_m *MockFleetManager) Create(ctx context.Context, maxPlayers int, userIds []string, latencies []runtime.FleetUserLatencies, metadata map[string]interface{}, callback runtime.FmCreateCallbackFn) error {
	ret := _m.Called(ctx, maxPlayers, userIds, latencies, metadata, callback)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []string, []runtime.FleetUserLatencies, map[string]interface{}, runtime.FmCreateCallbackFn) error); ok {
		r0 = rf(ctx, maxPlayers, userIds, latencies, metadata, callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFleetManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFleetManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - maxPlayers int
//   - userIds []string
//   - latencies []runtime.FleetUserLatencies
//   - metadata map[string]interface{}
//   - callback runtime.FmCreateCallbackFn
func (_e *MockFleetManager_Expecter) Create(ctx interface{}, maxPlayers interface{}, userIds interface{}, latencies interface{}, metadata interface{}, callback interface{}) *MockFleetManager_Create_Call {
	return &MockFleetManager_Create_Call{Call: _e.mock.On("Create", ctx, maxPlayers, userIds, latencies, metadata, callback)}
}

func (_c *MockFleetManager_Create_Call) Run(run func(ctx context.Context, maxPlayers int, userIds []string, latencies []runtime.FleetUserLatencies, metadata map[string]interface{}, callback runtime.FmCreateCallbackFn)) *MockFleetManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].([]string), args[3].([]runtime.FleetUserLatencies), args[4].(map[string]interface{}), args[5].(runtime.FmCreateCallbackFn))
	})
	return _c
}

func (_c *MockFleetManager_Create_Call) Return(err error) *MockFleetManager_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFleetManager_Create_Call) RunAndReturn(run func(context.Context, int, []string, []runtime.FleetUserLatencies, map[string]interface{}, runtime.FmCreateCallbackFn) error) *MockFleetManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockFleetManager) Get(ctx context.Context, id string) (*runtime.InstanceInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *runtime.InstanceInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*runtime.InstanceInfo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *runtime.InstanceInfo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.InstanceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFleetManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFleetManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFleetManager_Expecter) Get(ctx interface{}, id interface{}) *MockFleetManager_Get_Call {
	return &MockFleetManager_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockFleetManager_Get_Call) Run(run func(ctx context.Context, id string)) *MockFleetManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFleetManager_Get_Call) Return(instance *runtime.InstanceInfo, err error) *MockFleetManager_Get_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockFleetManager_Get_Call) RunAndReturn(run func(context.Context, string) (*runtime.InstanceInfo, error)) *MockFleetManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Join provides a mock function with given fields: ctx, id, userIds, metadata
func (_m *MockFleetManager) Join(ctx context.Context, id string, userIds []string, metadata map[string]string) (*runtime.JoinInfo, error) {
	ret := _m.Called(ctx, id, userIds, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Join")
	}

	var r0 *runtime.JoinInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, map[string]string) (*runtime.JoinInfo, error)); ok {
		return rf(ctx, id, userIds, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, map[string]string) *runtime.JoinInfo); ok {
		r0 = rf(ctx, id, userIds, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.JoinInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, map[string]string) error); ok {
		r1 = rf(ctx, id, userIds, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFleetManager_Join_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Join'
type MockFleetManager_Join_Call struct {
	*mock.Call
}

// Join is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userIds []string
//   - metadata map[string]string
func (_e *MockFleetManager_Expecter) Join(ctx interface{}, id interface{}, userIds interface{}, metadata interface{}) *MockFleetManager_Join_Call {
	return &MockFleetManager_Join_Call{Call: _e.mock.On("Join", ctx, id, userIds, metadata)}
}

func (_c *MockFleetManager_Join_Call) Run(run func(ctx context.Context, id string, userIds []string, metadata map[string]string)) *MockFleetManager_Join_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockFleetManager_Join_Call) Return(joinInfo *runtime.JoinInfo, err error) *MockFleetManager_Join_Call {
	_c.Call.Return(joinInfo, err)
	return _c
}

func (_c *MockFleetManager_Join_Call) RunAndReturn(run func(context.Context, string, []string, map[string]string) (*runtime.JoinInfo, error)) *MockFleetManager_Join_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, query, limit, previousCursor
func (_m *MockFleetManager) List(ctx context.Context, query string, limit int, previousCursor string) ([]*runtime.InstanceInfo, string, error) {
	ret := _m.Called(ctx, query, limit, previousCursor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*runtime.InstanceInfo
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) ([]*runtime.InstanceInfo, string, error)); ok {
		return rf(ctx, query, limit, previousCursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) []*runtime.InstanceInfo); ok {
		r0 = rf(ctx, query, limit, previousCursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*runtime.InstanceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, string) string); ok {
		r1 = rf(ctx, query, limit, previousCursor)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, string) error); ok {
		r2 = rf(ctx, query, limit, previousCursor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFleetManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFleetManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
//   - previousCursor string
func (_e *MockFleetManager_Expecter) List(ctx interface{}, query interface{}, limit interface{}, previousCursor interface{}) *MockFleetManager_List_Call {
	return &MockFleetManager_List_Call{Call: _e.mock.On("List", ctx, query, limit, previousCursor)}
}

func (_c *MockFleetManager_List_Call) Run(run func(ctx context.Context, query string, limit int, previousCursor string)) *MockFleetManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockFleetManager_List_Call) Return(list []*runtime.InstanceInfo, nextCursor string, err error) *MockFleetManager_List_Call {
	_c.Call.Return(list, nextCursor, err)
	return _c
}

func (_c *MockFleetManager_List_Call) RunAndReturn(run func(context.Context, string, int, string) ([]*runtime.InstanceInfo, string, error)) *MockFleetManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFleetManager creates a new instance of MockFleetManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFleetManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFleetManager {
	mock := &MockFleetManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
