// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockWalletLedgerItem is an autogenerated mock type for the WalletLedgerItem type
type MockWalletLedgerItem struct {
	mock.Mock
}

type MockWalletLedgerItem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletLedgerItem) EXPECT() *MockWalletLedgerItem_Expecter {
	return &MockWalletLedgerItem_Expecter{mock: &_m.Mock}
}

// GetChangeset provides a mock function with no fields
func (_m *MockWalletLedgerItem) GetChangeset() map[string]int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChangeset")
	}

	var r0 map[string]int64
	if rf, ok := ret.Get(0).(func() map[string]int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	return r0
}

// MockWalletLedgerItem_GetChangeset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChangeset'
type MockWalletLedgerItem_GetChangeset_Call struct {
	*mock.Call
}

// GetChangeset is a helper method to define mock.On call
func (_e *MockWalletLedgerItem_Expecter) GetChangeset() *MockWalletLedgerItem_GetChangeset_Call {
	return &MockWalletLedgerItem_GetChangeset_Call{Call: _e.mock.On("GetChangeset")}
}

func (_c *MockWalletLedgerItem_GetChangeset_Call) Run(run func()) *MockWalletLedgerItem_GetChangeset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWalletLedgerItem_GetChangeset_Call) Return(_a0 map[string]int64) *MockWalletLedgerItem_GetChangeset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletLedgerItem_GetChangeset_Call) RunAndReturn(run func() map[string]int64) *MockWalletLedgerItem_GetChangeset_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreateTime provides a mock function with no fields
func (_m *MockWalletLedgerItem) GetCreateTime() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreateTime")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockWalletLedgerItem_GetCreateTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreateTime'
type MockWalletLedgerItem_GetCreateTime_Call struct {
	*mock.Call
}

// GetCreateTime is a helper method to define mock.On call
func (_e *MockWalletLedgerItem_Expecter) GetCreateTime() *MockWalletLedgerItem_GetCreateTime_Call {
	return &MockWalletLedgerItem_GetCreateTime_Call{Call: _e.mock.On("GetCreateTime")}
}

func (_c *MockWalletLedgerItem_GetCreateTime_Call) Run(run func()) *MockWalletLedgerItem_GetCreateTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWalletLedgerItem_GetCreateTime_Call) Return(_a0 int64) *MockWalletLedgerItem_GetCreateTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletLedgerItem_GetCreateTime_Call) RunAndReturn(run func() int64) *MockWalletLedgerItem_GetCreateTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function with no fields
func (_m *MockWalletLedgerItem) GetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockWalletLedgerItem_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockWalletLedgerItem_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockWalletLedgerItem_Expecter) GetID() *MockWalletLedgerItem_GetID_Call {
	return &MockWalletLedgerItem_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockWalletLedgerItem_GetID_Call) Run(run func()) *MockWalletLedgerItem_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWalletLedgerItem_GetID_Call) Return(_a0 string) *MockWalletLedgerItem_GetID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletLedgerItem_GetID_Call) RunAndReturn(run func() string) *MockWalletLedgerItem_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function with no fields
func (_m *MockWalletLedgerItem) GetMetadata() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockWalletLedgerItem_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type MockWalletLedgerItem_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
func (_e *MockWalletLedgerItem_Expecter) GetMetadata() *MockWalletLedgerItem_GetMetadata_Call {
	return &MockWalletLedgerItem_GetMetadata_Call{Call: _e.mock.On("GetMetadata")}
}

func (_c *MockWalletLedgerItem_GetMetadata_Call) Run(run func()) *MockWalletLedgerItem_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWalletLedgerItem_GetMetadata_Call) Return(_a0 map[string]interface{}) *MockWalletLedgerItem_GetMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletLedgerItem_GetMetadata_Call) RunAndReturn(run func() map[string]interface{}) *MockWalletLedgerItem_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdateTime provides a mock function with no fields
func (_m *MockWalletLedgerItem) GetUpdateTime() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUpdateTime")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockWalletLedgerItem_GetUpdateTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdateTime'
type MockWalletLedgerItem_GetUpdateTime_Call struct {
	*mock.Call
}

// GetUpdateTime is a helper method to define mock.On call
func (_e *MockWalletLedgerItem_Expecter) GetUpdateTime() *MockWalletLedgerItem_GetUpdateTime_Call {
	return &MockWalletLedgerItem_GetUpdateTime_Call{Call: _e.mock.On("GetUpdateTime")}
}

func (_c *MockWalletLedgerItem_GetUpdateTime_Call) Run(run func()) *MockWalletLedgerItem_GetUpdateTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWalletLedgerItem_GetUpdateTime_Call) Return(_a0 int64) *MockWalletLedgerItem_GetUpdateTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletLedgerItem_GetUpdateTime_Call) RunAndReturn(run func() int64) *MockWalletLedgerItem_GetUpdateTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserID provides a mock function with no fields
func (_m *MockWalletLedgerItem) GetUserID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockWalletLedgerItem_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockWalletLedgerItem_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
func (_e *MockWalletLedgerItem_Expecter) GetUserID() *MockWalletLedgerItem_GetUserID_Call {
	return &MockWalletLedgerItem_GetUserID_Call{Call: _e.mock.On("GetUserID")}
}

func (_c *MockWalletLedgerItem_GetUserID_Call) Run(run func()) *MockWalletLedgerItem_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWalletLedgerItem_GetUserID_Call) Return(_a0 string) *MockWalletLedgerItem_GetUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletLedgerItem_GetUserID_Call) RunAndReturn(run func() string) *MockWalletLedgerItem_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletLedgerItem creates a new instance of MockWalletLedgerItem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletLedgerItem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletLedgerItem {
	mock := &MockWalletLedgerItem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
