steps:
  - command: make lint
    plugins:
      - docker#v5.1.0:
          image: "golangci/golangci-lint:v1.57-alpine"
          volumes:
            - ".cache/go-build:.cache/go-build"
            - ".cache/golangci-lint:.cache/golangci-lint"
      - cache#v1.0.0:
          path: .cache/golangci-lint
          restore: pipeline
          save: pipeline