# example of values needed to setup the rollup application

[app_options]
cpu-profile=""
app-db-backend=""
db-backend=""
trace-store=""
grpc-only=false
inter-block-cache=true
unsafe-skip-upgrades=40
home="fooabr"
inv-check-period=30
min-gas-prices="1stake"
halt-height=40
halt-time=1979-05-27T07:32:00Z
min-retain-blocks=20
trace=false
index-events=[]
IAVL-cache-size=20
disable-IVAL-fast-node=true
x-crisis-skip-assert-invariants=true
evm-max-tx-gas-wanted=100
evm-tracer=""
state-sync.snapshot-interval=30
state-sync.snapshot-keep-recent=40

[node_config]
aggregator=false
DA-layer=""
DA-config=""
light=false

[node_config.block_manager_config]
DA-start-height=0
DA-block-time=1979-05-27T07:32:00Z
block-time="10s"
namespace-id=""
fraud-proofs=true
