// Code generated by world sdk generate. DO NOT EDIT.

//go:build !sdkgen

package event

import (
	pbevent "github.com/argus-labs/world-engine/pkg/template/multi-shard/shards/game/gen/pkg/template/multi-shard/shards/game/event"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func (c PlayerDeparture) ToProto() *pbevent.PlayerDeparture {
	p := &pbevent.PlayerDeparture{}
	p.ArgusAuthID = string(c.ArgusAuthID)
	return p
}

func (c PlayerDeparture) FromProto(p *pbevent.PlayerDeparture) PlayerDeparture {
	if p == nil {
		return c
	}
	c.ArgusAuthID = string(p.ArgusAuthID)
	return c
}

func (c PlayerDeparture) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal PlayerDeparture: " + err.Error())
	}
	return data
}

func (c PlayerDeparture) UnmarshalWire(data []byte) (any, error) {
	var p pbevent.PlayerDeparture
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c PlayerDeparture) ProtoDescriptor() protoreflect.MessageDescriptor {
	return (&pbevent.PlayerDeparture{}).ProtoReflect().Descriptor()
}

func (c PlayerMovement) ToProto() *pbevent.PlayerMovement {
	p := &pbevent.PlayerMovement{}
	p.ArgusAuthID = string(c.ArgusAuthID)
	p.ArgusAuthName = string(c.ArgusAuthName)
	p.X = uint32(c.X)
	p.Y = uint32(c.Y)
	return p
}

func (c PlayerMovement) FromProto(p *pbevent.PlayerMovement) PlayerMovement {
	if p == nil {
		return c
	}
	c.ArgusAuthID = string(p.ArgusAuthID)
	c.ArgusAuthName = string(p.ArgusAuthName)
	c.X = uint32(p.X)
	c.Y = uint32(p.Y)
	return c
}

func (c PlayerMovement) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal PlayerMovement: " + err.Error())
	}
	return data
}

func (c PlayerMovement) UnmarshalWire(data []byte) (any, error) {
	var p pbevent.PlayerMovement
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c PlayerMovement) ProtoDescriptor() protoreflect.MessageDescriptor {
	return (&pbevent.PlayerMovement{}).ProtoReflect().Descriptor()
}

func (c PlayerSpawn) ToProto() *pbevent.PlayerSpawn {
	p := &pbevent.PlayerSpawn{}
	p.ArgusAuthID = string(c.ArgusAuthID)
	p.ArgusAuthName = string(c.ArgusAuthName)
	p.X = uint32(c.X)
	p.Y = uint32(c.Y)
	return p
}

func (c PlayerSpawn) FromProto(p *pbevent.PlayerSpawn) PlayerSpawn {
	if p == nil {
		return c
	}
	c.ArgusAuthID = string(p.ArgusAuthID)
	c.ArgusAuthName = string(p.ArgusAuthName)
	c.X = uint32(p.X)
	c.Y = uint32(p.Y)
	return c
}

func (c PlayerSpawn) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal PlayerSpawn: " + err.Error())
	}
	return data
}

func (c PlayerSpawn) UnmarshalWire(data []byte) (any, error) {
	var p pbevent.PlayerSpawn
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c PlayerSpawn) ProtoDescriptor() protoreflect.MessageDescriptor {
	return (&pbevent.PlayerSpawn{}).ProtoReflect().Descriptor()
}
