---

- name: Fetch genesis.json
  fetch: "src=/home/argusd/.argus/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: argusd

- name: Fetch config.toml
  fetch: "src=/home/argusd/.argus/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: argusd
