// Code generated by world sdk generate. DO NOT EDIT.

//go:build !sdkgen

package component

import (
	pbcomponent "github.com/argus-labs/world-engine/pkg/template/multi-shard/shards/game/gen/pkg/template/multi-shard/shards/game/component"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/known/timestamppb"
	"time"
)

func (c OnlineStatus) ToProto() *pbcomponent.OnlineStatus {
	p := &pbcomponent.OnlineStatus{}
	p.Online = bool(c.Online)
	p.LastActive = timestamppb.New(c.LastActive)
	return p
}

func (c OnlineStatus) FromProto(p *pbcomponent.OnlineStatus) OnlineStatus {
	if p == nil {
		return c
	}
	c.Online = bool(p.Online)
	if p.LastActive != nil {
		c.LastActive = p.LastActive.AsTime()
	}
	return c
}

func (c OnlineStatus) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal OnlineStatus: " + err.Error())
	}
	return data
}

func (c OnlineStatus) UnmarshalWire(data []byte) (any, error) {
	var p pbcomponent.OnlineStatus
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c OnlineStatus) ProtoDescriptor() protoreflect.MessageDescriptor {
	return (&pbcomponent.OnlineStatus{}).ProtoReflect().Descriptor()
}

func (c OnlineStatus) SizeWire() int {
	n := 0
	if c.Online {
		n += protowire.SizeTag(1) + 1
	}
	n += protowire.SizeTag(2) + protowire.SizeBytes(sizeWireTimestamp(c.LastActive))
	return n
}

func (c OnlineStatus) AppendWire(b []byte) []byte {
	if c.Online {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, 1)
	}
	b = protowire.AppendTag(b, 2, protowire.BytesType)
	b = protowire.AppendVarint(b, uint64(sizeWireTimestamp(c.LastActive)))
	b = appendWireTimestamp(b, c.LastActive)
	return b
}

func (c PlayerTag) ToProto() *pbcomponent.PlayerTag {
	p := &pbcomponent.PlayerTag{}
	p.ArgusAuthID = string(c.ArgusAuthID)
	p.ArgusAuthName = string(c.ArgusAuthName)
	return p
}

func (c PlayerTag) FromProto(p *pbcomponent.PlayerTag) PlayerTag {
	if p == nil {
		return c
	}
	c.ArgusAuthID = string(p.ArgusAuthID)
	c.ArgusAuthName = string(p.ArgusAuthName)
	return c
}

func (c PlayerTag) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal PlayerTag: " + err.Error())
	}
	return data
}

func (c PlayerTag) UnmarshalWire(data []byte) (any, error) {
	var p pbcomponent.PlayerTag
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c PlayerTag) ProtoDescriptor() protoreflect.MessageDescriptor {
	return (&pbcomponent.PlayerTag{}).ProtoReflect().Descriptor()
}

func (c PlayerTag) SizeWire() int {
	n := 0
	if len(c.ArgusAuthID) > 0 {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(c.ArgusAuthID))
	}
	if len(c.ArgusAuthName) > 0 {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(c.ArgusAuthName))
	}
	return n
}

func (c PlayerTag) AppendWire(b []byte) []byte {
	if len(c.ArgusAuthID) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, string(c.ArgusAuthID))
	}
	if len(c.ArgusAuthName) > 0 {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, string(c.ArgusAuthName))
	}
	return b
}

func (c Position) ToProto() *pbcomponent.Position {
	p := &pbcomponent.Position{}
	p.X = int64(c.X)
	p.Y = int64(c.Y)
	return p
}

func (c Position) FromProto(p *pbcomponent.Position) Position {
	if p == nil {
		return c
	}
	c.X = int(p.X)
	c.Y = int(p.Y)
	return c
}

func (c Position) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal Position: " + err.Error())
	}
	return data
}

func (c Position) UnmarshalWire(data []byte) (any, error) {
	var p pbcomponent.Position
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c Position) ProtoDescriptor() protoreflect.MessageDescriptor {
	return (&pbcomponent.Position{}).ProtoReflect().Descriptor()
}

func (c Position) SizeWire() int {
	n := 0
	if c.X != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(c.X))
	}
	if c.Y != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(c.Y))
	}
	return n
}

func (c Position) AppendWire(b []byte) []byte {
	if c.X != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(c.X))
	}
	if c.Y != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(c.Y))
	}
	return b
}

// sizeWireTimestamp is the encoded size of the google.protobuf.Timestamp holding t.
func sizeWireTimestamp(t time.Time) int {
	n := 0
	if s := t.Unix(); s != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(s))
	}
	if ns := t.Nanosecond(); ns != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(ns))
	}
	return n
}

// appendWireTimestamp writes the google.protobuf.Timestamp holding t.
func appendWireTimestamp(b []byte, t time.Time) []byte {
	if s := t.Unix(); s != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(s))
	}
	if ns := t.Nanosecond(); ns != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(ns))
	}
	return b
}
