// Code generated by world sdk generate. DO NOT EDIT.

//go:build !sdkgen

package component

import (
	component "github.com/argus-labs/world-engine/pkg/template/multi-shard/shards/game/gen/pkg/template/multi-shard/shards/game/component"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func (c OnlineStatus) ToProto() *component.OnlineStatus {
	p := &component.OnlineStatus{}
	p.Online = bool(c.Online)
	p.LastActive = timestamppb.New(c.LastActive)
	return p
}

func (c OnlineStatus) FromProto(p *component.OnlineStatus) OnlineStatus {
	if p == nil {
		return c
	}
	c.Online = bool(p.Online)
	if p.LastActive != nil {
		c.LastActive = p.LastActive.AsTime()
	}
	return c
}

func (c OnlineStatus) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal OnlineStatus: " + err.Error())
	}
	return data
}

func (c OnlineStatus) UnmarshalWire(data []byte) (any, error) {
	var p component.OnlineStatus
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c PlayerTag) ToProto() *component.PlayerTag {
	p := &component.PlayerTag{}
	p.ArgusAuthID = string(c.ArgusAuthID)
	p.ArgusAuthName = string(c.ArgusAuthName)
	return p
}

func (c PlayerTag) FromProto(p *component.PlayerTag) PlayerTag {
	if p == nil {
		return c
	}
	c.ArgusAuthID = string(p.ArgusAuthID)
	c.ArgusAuthName = string(p.ArgusAuthName)
	return c
}

func (c PlayerTag) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal PlayerTag: " + err.Error())
	}
	return data
}

func (c PlayerTag) UnmarshalWire(data []byte) (any, error) {
	var p component.PlayerTag
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c Position) ToProto() *component.Position {
	p := &component.Position{}
	p.X = int64(c.X)
	p.Y = int64(c.Y)
	return p
}

func (c Position) FromProto(p *component.Position) Position {
	if p == nil {
		return c
	}
	c.X = int(p.X)
	c.Y = int(p.Y)
	return c
}

func (c Position) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal Position: " + err.Error())
	}
	return data
}

func (c Position) UnmarshalWire(data []byte) (any, error) {
	var p component.Position
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}
