// Code generated by world sdk generate. DO NOT EDIT.

package system

import (
	"fmt"

	"github.com/argus-labs/world-engine/pkg/cardinal"
	gen "github.com/argus-labs/world-engine/pkg/plugin/lobby/gen"
	"google.golang.org/protobuf/proto"
)

func (c AssignShardCommand) toProto() *gen.AssignShardCommand {
	p := &gen.AssignShardCommand{}
	p.LobbyID = string(c.LobbyID)
	p.RequestID = string(c.RequestID)
	p.GameWorld = c.GameWorld.toProto()
	p.Reason = string(c.Reason)
	return p
}

func assignShardCommandFromProto(p *gen.AssignShardCommand) AssignShardCommand {
	var c AssignShardCommand
	if p == nil {
		return c
	}
	c.LobbyID = string(p.LobbyID)
	c.RequestID = string(p.RequestID)
	c.GameWorld = shardAddressFromProto(p.GameWorld)
	c.Reason = string(p.Reason)
	return c
}

type assignShardCommandCodec struct{}

func (assignShardCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(AssignShardCommand)
	if !ok {
		return nil, fmt.Errorf("expected AssignShardCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (assignShardCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.AssignShardCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return assignShardCommandFromProto(&p), nil
}

func (c CreateLobbyCommand) toProto() *gen.CreateLobbyCommand {
	p := &gen.CreateLobbyCommand{}
	p.RequestID = string(c.RequestID)
	p.Preset = string(c.Preset)
	p.PlayerPassthroughData = []byte(c.PlayerPassthroughData)
	p.SessionPassthroughData = []byte(c.SessionPassthroughData)
	return p
}

func createLobbyCommandFromProto(p *gen.CreateLobbyCommand) CreateLobbyCommand {
	var c CreateLobbyCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	c.Preset = string(p.Preset)
	c.PlayerPassthroughData = []byte(p.PlayerPassthroughData)
	c.SessionPassthroughData = []byte(p.SessionPassthroughData)
	return c
}

type createLobbyCommandCodec struct{}

func (createLobbyCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(CreateLobbyCommand)
	if !ok {
		return nil, fmt.Errorf("expected CreateLobbyCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (createLobbyCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.CreateLobbyCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return createLobbyCommandFromProto(&p), nil
}

func (c GenerateInviteCodeCommand) toProto() *gen.GenerateInviteCodeCommand {
	p := &gen.GenerateInviteCodeCommand{}
	p.RequestID = string(c.RequestID)
	return p
}

func generateInviteCodeCommandFromProto(p *gen.GenerateInviteCodeCommand) GenerateInviteCodeCommand {
	var c GenerateInviteCodeCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	return c
}

type generateInviteCodeCommandCodec struct{}

func (generateInviteCodeCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(GenerateInviteCodeCommand)
	if !ok {
		return nil, fmt.Errorf("expected GenerateInviteCodeCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (generateInviteCodeCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.GenerateInviteCodeCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return generateInviteCodeCommandFromProto(&p), nil
}

func (c GetAllPlayersCommand) toProto() *gen.GetAllPlayersCommand {
	p := &gen.GetAllPlayersCommand{}
	p.RequestID = string(c.RequestID)
	return p
}

func getAllPlayersCommandFromProto(p *gen.GetAllPlayersCommand) GetAllPlayersCommand {
	var c GetAllPlayersCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	return c
}

type getAllPlayersCommandCodec struct{}

func (getAllPlayersCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(GetAllPlayersCommand)
	if !ok {
		return nil, fmt.Errorf("expected GetAllPlayersCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (getAllPlayersCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.GetAllPlayersCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return getAllPlayersCommandFromProto(&p), nil
}

func (c GetLobbyCommand) toProto() *gen.GetLobbyCommand {
	p := &gen.GetLobbyCommand{}
	p.RequestID = string(c.RequestID)
	return p
}

func getLobbyCommandFromProto(p *gen.GetLobbyCommand) GetLobbyCommand {
	var c GetLobbyCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	return c
}

type getLobbyCommandCodec struct{}

func (getLobbyCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(GetLobbyCommand)
	if !ok {
		return nil, fmt.Errorf("expected GetLobbyCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (getLobbyCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.GetLobbyCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return getLobbyCommandFromProto(&p), nil
}

func (c GetPlayerCommand) toProto() *gen.GetPlayerCommand {
	p := &gen.GetPlayerCommand{}
	p.RequestID = string(c.RequestID)
	p.PlayerID = string(c.PlayerID)
	return p
}

func getPlayerCommandFromProto(p *gen.GetPlayerCommand) GetPlayerCommand {
	var c GetPlayerCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	c.PlayerID = string(p.PlayerID)
	return c
}

type getPlayerCommandCodec struct{}

func (getPlayerCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(GetPlayerCommand)
	if !ok {
		return nil, fmt.Errorf("expected GetPlayerCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (getPlayerCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.GetPlayerCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return getPlayerCommandFromProto(&p), nil
}

func (c HeartbeatCommand) toProto() *gen.HeartbeatCommand {
	p := &gen.HeartbeatCommand{}
	return p
}

func heartbeatCommandFromProto(p *gen.HeartbeatCommand) HeartbeatCommand {
	var c HeartbeatCommand
	if p == nil {
		return c
	}
	return c
}

type heartbeatCommandCodec struct{}

func (heartbeatCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(HeartbeatCommand)
	if !ok {
		return nil, fmt.Errorf("expected HeartbeatCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (heartbeatCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.HeartbeatCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return heartbeatCommandFromProto(&p), nil
}

func (c JoinLobbyCommand) toProto() *gen.JoinLobbyCommand {
	p := &gen.JoinLobbyCommand{}
	p.RequestID = string(c.RequestID)
	p.InviteCode = string(c.InviteCode)
	p.TeamID = string(c.TeamID)
	p.PlayerPassthroughData = []byte(c.PlayerPassthroughData)
	return p
}

func joinLobbyCommandFromProto(p *gen.JoinLobbyCommand) JoinLobbyCommand {
	var c JoinLobbyCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	c.InviteCode = string(p.InviteCode)
	c.TeamID = string(p.TeamID)
	c.PlayerPassthroughData = []byte(p.PlayerPassthroughData)
	return c
}

type joinLobbyCommandCodec struct{}

func (joinLobbyCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(JoinLobbyCommand)
	if !ok {
		return nil, fmt.Errorf("expected JoinLobbyCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (joinLobbyCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.JoinLobbyCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return joinLobbyCommandFromProto(&p), nil
}

func (c JoinTeamCommand) toProto() *gen.JoinTeamCommand {
	p := &gen.JoinTeamCommand{}
	p.RequestID = string(c.RequestID)
	p.TeamID = string(c.TeamID)
	return p
}

func joinTeamCommandFromProto(p *gen.JoinTeamCommand) JoinTeamCommand {
	var c JoinTeamCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	c.TeamID = string(p.TeamID)
	return c
}

type joinTeamCommandCodec struct{}

func (joinTeamCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(JoinTeamCommand)
	if !ok {
		return nil, fmt.Errorf("expected JoinTeamCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (joinTeamCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.JoinTeamCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return joinTeamCommandFromProto(&p), nil
}

func (c KickPlayerCommand) toProto() *gen.KickPlayerCommand {
	p := &gen.KickPlayerCommand{}
	p.RequestID = string(c.RequestID)
	p.TargetPlayerID = string(c.TargetPlayerID)
	return p
}

func kickPlayerCommandFromProto(p *gen.KickPlayerCommand) KickPlayerCommand {
	var c KickPlayerCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	c.TargetPlayerID = string(p.TargetPlayerID)
	return c
}

type kickPlayerCommandCodec struct{}

func (kickPlayerCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(KickPlayerCommand)
	if !ok {
		return nil, fmt.Errorf("expected KickPlayerCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (kickPlayerCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.KickPlayerCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return kickPlayerCommandFromProto(&p), nil
}

func (c LeaveLobbyCommand) toProto() *gen.LeaveLobbyCommand {
	p := &gen.LeaveLobbyCommand{}
	p.RequestID = string(c.RequestID)
	return p
}

func leaveLobbyCommandFromProto(p *gen.LeaveLobbyCommand) LeaveLobbyCommand {
	var c LeaveLobbyCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	return c
}

type leaveLobbyCommandCodec struct{}

func (leaveLobbyCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(LeaveLobbyCommand)
	if !ok {
		return nil, fmt.Errorf("expected LeaveLobbyCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (leaveLobbyCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.LeaveLobbyCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return leaveLobbyCommandFromProto(&p), nil
}

func (c NotifySessionEndCommand) toProto() *gen.NotifySessionEndCommand {
	p := &gen.NotifySessionEndCommand{}
	p.LobbyID = string(c.LobbyID)
	return p
}

func notifySessionEndCommandFromProto(p *gen.NotifySessionEndCommand) NotifySessionEndCommand {
	var c NotifySessionEndCommand
	if p == nil {
		return c
	}
	c.LobbyID = string(p.LobbyID)
	return c
}

type notifySessionEndCommandCodec struct{}

func (notifySessionEndCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(NotifySessionEndCommand)
	if !ok {
		return nil, fmt.Errorf("expected NotifySessionEndCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (notifySessionEndCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.NotifySessionEndCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return notifySessionEndCommandFromProto(&p), nil
}

func (c SetReadyCommand) toProto() *gen.SetReadyCommand {
	p := &gen.SetReadyCommand{}
	p.RequestID = string(c.RequestID)
	p.IsReady = bool(c.IsReady)
	return p
}

func setReadyCommandFromProto(p *gen.SetReadyCommand) SetReadyCommand {
	var c SetReadyCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	c.IsReady = bool(p.IsReady)
	return c
}

type setReadyCommandCodec struct{}

func (setReadyCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(SetReadyCommand)
	if !ok {
		return nil, fmt.Errorf("expected SetReadyCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (setReadyCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.SetReadyCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return setReadyCommandFromProto(&p), nil
}

func (c ShardAddress) toProto() *gen.ShardAddress {
	p := &gen.ShardAddress{}
	p.Region = string(c.Region)
	p.Organization = string(c.Organization)
	p.Project = string(c.Project)
	p.ShardID = string(c.ShardID)
	return p
}

func shardAddressFromProto(p *gen.ShardAddress) ShardAddress {
	var c ShardAddress
	if p == nil {
		return c
	}
	c.Region = string(p.Region)
	c.Organization = string(p.Organization)
	c.Project = string(p.Project)
	c.ShardID = string(p.ShardID)
	return c
}

func (c StartSessionCommand) toProto() *gen.StartSessionCommand {
	p := &gen.StartSessionCommand{}
	p.RequestID = string(c.RequestID)
	return p
}

func startSessionCommandFromProto(p *gen.StartSessionCommand) StartSessionCommand {
	var c StartSessionCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	return c
}

type startSessionCommandCodec struct{}

func (startSessionCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(StartSessionCommand)
	if !ok {
		return nil, fmt.Errorf("expected StartSessionCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (startSessionCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.StartSessionCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return startSessionCommandFromProto(&p), nil
}

func (c TransferLeaderCommand) toProto() *gen.TransferLeaderCommand {
	p := &gen.TransferLeaderCommand{}
	p.RequestID = string(c.RequestID)
	p.TargetPlayerID = string(c.TargetPlayerID)
	return p
}

func transferLeaderCommandFromProto(p *gen.TransferLeaderCommand) TransferLeaderCommand {
	var c TransferLeaderCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	c.TargetPlayerID = string(p.TargetPlayerID)
	return c
}

type transferLeaderCommandCodec struct{}

func (transferLeaderCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(TransferLeaderCommand)
	if !ok {
		return nil, fmt.Errorf("expected TransferLeaderCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (transferLeaderCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.TransferLeaderCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return transferLeaderCommandFromProto(&p), nil
}

func (c UpdatePlayerPassthroughCommand) toProto() *gen.UpdatePlayerPassthroughCommand {
	p := &gen.UpdatePlayerPassthroughCommand{}
	p.RequestID = string(c.RequestID)
	p.PassthroughData = []byte(c.PassthroughData)
	return p
}

func updatePlayerPassthroughCommandFromProto(p *gen.UpdatePlayerPassthroughCommand) UpdatePlayerPassthroughCommand {
	var c UpdatePlayerPassthroughCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	c.PassthroughData = []byte(p.PassthroughData)
	return c
}

type updatePlayerPassthroughCommandCodec struct{}

func (updatePlayerPassthroughCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(UpdatePlayerPassthroughCommand)
	if !ok {
		return nil, fmt.Errorf("expected UpdatePlayerPassthroughCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (updatePlayerPassthroughCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.UpdatePlayerPassthroughCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return updatePlayerPassthroughCommandFromProto(&p), nil
}

func (c UpdateSessionPassthroughCommand) toProto() *gen.UpdateSessionPassthroughCommand {
	p := &gen.UpdateSessionPassthroughCommand{}
	p.RequestID = string(c.RequestID)
	p.PassthroughData = []byte(c.PassthroughData)
	return p
}

func updateSessionPassthroughCommandFromProto(p *gen.UpdateSessionPassthroughCommand) UpdateSessionPassthroughCommand {
	var c UpdateSessionPassthroughCommand
	if p == nil {
		return c
	}
	c.RequestID = string(p.RequestID)
	c.PassthroughData = []byte(p.PassthroughData)
	return c
}

type updateSessionPassthroughCommandCodec struct{}

func (updateSessionPassthroughCommandCodec) Marshal(p cardinal.Command) ([]byte, error) {
	c, ok := p.(UpdateSessionPassthroughCommand)
	if !ok {
		return nil, fmt.Errorf("expected UpdateSessionPassthroughCommand, got %T", p)
	}
	return proto.Marshal(c.toProto())
}

func (updateSessionPassthroughCommandCodec) Unmarshal(data []byte) (cardinal.Command, error) {
	var p gen.UpdateSessionPassthroughCommand
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return updateSessionPassthroughCommandFromProto(&p), nil
}

func init() {
	cardinal.RegisterCommandCodec("lobby_assign_shard", assignShardCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_create", createLobbyCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_generate_invite", generateInviteCodeCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_get_all_players", getAllPlayersCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_get_lobby", getLobbyCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_get_player", getPlayerCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_heartbeat", heartbeatCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_join", joinLobbyCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_join_team", joinTeamCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_kick", kickPlayerCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_leave", leaveLobbyCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_notify_session_end", notifySessionEndCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_set_ready", setReadyCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_start_session", startSessionCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_transfer_leader", transferLeaderCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_update_player_passthrough", updatePlayerPassthroughCommandCodec{})
	cardinal.RegisterCommandCodec("lobby_update_session_passthrough", updateSessionPassthroughCommandCodec{})
}
