name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-cardinal:
    name: Build Cardinal
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cardinal
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Build Cardinal Docker Image
        run: docker build .
