name: Lint

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.21.0
      GOLANGCI_VERSION: v1.54.2
    strategy:
      matrix:
        lint-workdir: [cardinal]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "**/*.sum"
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@${{ env.GOLANGCI_VERSION }}
      - name: Lint
        working-directory: ${{ matrix.lint-workdir }}
        run: golangci-lint run  --timeout=10m --concurrency 4 -v
