shardID: gameplay
image: rampage/gameplay
imageTag: local
poolSize: 2
tickRate: 20
organization: argus
project: rampage
region: us-west1
auth:
  mode: DEV
debug: true
snapshotStorageType: JETSTREAM
nats:
  url: nats://nats.nats.svc.cluster.local:4222
database:
  dsn: postgres://postgres:postgres@rampage-db.rampage.svc.cluster.local:5432/rampage?sslmode=disable
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: '1'
    memory: 1Gi
routing:
  provider: none
