// Code generated by world sdk generate. DO NOT EDIT.

//go:build !sdkgen

package component

import (
	pbcomponent "github.com/argus-labs/world-engine/pkg/plugin/lobby/gen/pkg/plugin/lobby/component"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func (c LobbyComponent) ToProto() *pbcomponent.LobbyComponent {
	p := &pbcomponent.LobbyComponent{}
	p.ID = string(c.ID)
	p.LeaderID = string(c.LeaderID)
	for i0 := range c.PlayerIDs {
		p.PlayerIDs = append(p.PlayerIDs, string(c.PlayerIDs[i0]))
	}
	p.PlayerCount = int64(c.PlayerCount)
	for i0 := range c.Teams {
		p.Teams = append(p.Teams, c.Teams[i0].ToProto())
	}
	p.TeamCount = int64(c.TeamCount)
	p.InviteCode = string(c.InviteCode)
	p.GameWorld = c.GameWorld.ToProto()
	p.Session = c.Session.ToProto()
	p.CreatedAt = int64(c.CreatedAt)
	return p
}

func (c LobbyComponent) FromProto(p *pbcomponent.LobbyComponent) LobbyComponent {
	if p == nil {
		return c
	}
	c.ID = string(p.ID)
	c.LeaderID = string(p.LeaderID)
	for i, e := range p.PlayerIDs {
		if i >= 16 {
			break
		}
		c.PlayerIDs[i] = string(e)
	}
	c.PlayerCount = int(p.PlayerCount)
	for i, e := range p.Teams {
		if i >= 4 {
			break
		}
		var v Team
		c.Teams[i] = v.FromProto(e)
	}
	c.TeamCount = int(p.TeamCount)
	c.InviteCode = string(p.InviteCode)
	c.GameWorld = c.GameWorld.FromProto(p.GameWorld)
	c.Session = c.Session.FromProto(p.Session)
	c.CreatedAt = int64(p.CreatedAt)
	return c
}

func (c LobbyComponent) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal LobbyComponent: " + err.Error())
	}
	return data
}

func (c LobbyComponent) UnmarshalWire(data []byte) (any, error) {
	var p pbcomponent.LobbyComponent
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c LobbyComponent) ProtoDescriptor() protoreflect.MessageDescriptor {
	return (&pbcomponent.LobbyComponent{}).ProtoReflect().Descriptor()
}

func (c PlayerComponent) ToProto() *pbcomponent.PlayerComponent {
	p := &pbcomponent.PlayerComponent{}
	p.PlayerID = string(c.PlayerID)
	p.LobbyID = string(c.LobbyID)
	p.TeamID = string(c.TeamID)
	p.IsReady = bool(c.IsReady)
	p.PassthroughData = string(c.PassthroughData)
	p.JoinedAt = int64(c.JoinedAt)
	return p
}

func (c PlayerComponent) FromProto(p *pbcomponent.PlayerComponent) PlayerComponent {
	if p == nil {
		return c
	}
	c.PlayerID = string(p.PlayerID)
	c.LobbyID = string(p.LobbyID)
	c.TeamID = string(p.TeamID)
	c.IsReady = bool(p.IsReady)
	c.PassthroughData = string(p.PassthroughData)
	c.JoinedAt = int64(p.JoinedAt)
	return c
}

func (c PlayerComponent) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal PlayerComponent: " + err.Error())
	}
	return data
}

func (c PlayerComponent) UnmarshalWire(data []byte) (any, error) {
	var p pbcomponent.PlayerComponent
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c PlayerComponent) ProtoDescriptor() protoreflect.MessageDescriptor {
	return (&pbcomponent.PlayerComponent{}).ProtoReflect().Descriptor()
}

func (c Session) ToProto() *pbcomponent.Session {
	p := &pbcomponent.Session{}
	p.State = string(c.State)
	p.PassthroughData = string(c.PassthroughData)
	p.PendingRequestID = string(c.PendingRequestID)
	p.PendingStartedAt = int64(c.PendingStartedAt)
	return p
}

func (c Session) FromProto(p *pbcomponent.Session) Session {
	if p == nil {
		return c
	}
	c.State = SessionState(p.State)
	c.PassthroughData = string(p.PassthroughData)
	c.PendingRequestID = string(p.PendingRequestID)
	c.PendingStartedAt = int64(p.PendingStartedAt)
	return c
}

func (c ShardAddress) ToProto() *pbcomponent.ShardAddress {
	p := &pbcomponent.ShardAddress{}
	p.Region = string(c.Region)
	p.Organization = string(c.Organization)
	p.Project = string(c.Project)
	p.ShardID = string(c.ShardID)
	return p
}

func (c ShardAddress) FromProto(p *pbcomponent.ShardAddress) ShardAddress {
	if p == nil {
		return c
	}
	c.Region = string(p.Region)
	c.Organization = string(p.Organization)
	c.Project = string(p.Project)
	c.ShardID = string(p.ShardID)
	return c
}

func (c Team) ToProto() *pbcomponent.Team {
	p := &pbcomponent.Team{}
	p.TeamID = string(c.TeamID)
	p.MaxPlayers = int64(c.MaxPlayers)
	p.PlayerCount = int64(c.PlayerCount)
	return p
}

func (c Team) FromProto(p *pbcomponent.Team) Team {
	if p == nil {
		return c
	}
	c.TeamID = string(p.TeamID)
	c.MaxPlayers = int(p.MaxPlayers)
	c.PlayerCount = int(p.PlayerCount)
	return c
}
