package types

import (
	"time"

	microv1 "github.com/argus-labs/world-engine/proto/gen/go/worldengine/micro/v1"
)

// LobbyState represents the current state of a lobby.
type LobbyState string

const (
	LobbyStateWaiting LobbyState = "waiting" // Parties gathering, can join/leave
	LobbyStateReady   LobbyState = "ready"   // All parties ready, can start match
	LobbyStateInGame  LobbyState = "in_game" // Match active
	LobbyStateEnded   LobbyState = "ended"   // Game finished
)

// LobbyTeam represents a team in a matchmade lobby.
type LobbyTeam struct {
	Name     string   `json:"name"`
	PartyIDs []string `json:"party_ids"`
}

// Lobby is a container for parties throughout the game lifecycle.
// Created either manually or automatically when Match is received from Matchmaking Shard.
// Note: MatchID is the primary key - there is no separate lobby_id.
type Lobby struct {
	// MatchID is the primary identifier for the lobby.
	// This is generated by Matchmaking Shard and used as the lobby key.
	MatchID string `json:"match_id"`

	HostPartyID string   `json:"host_party_id"`
	Parties     []string `json:"parties"` // Flat list of party IDs

	// Team assignments from Match (only for matchmade lobbies)
	Teams []LobbyTeam `json:"teams,omitempty"`

	State LobbyState `json:"state"`

	// Matchmaking-related fields (set when created from Match)
	MatchProfileName   string                  `json:"match_profile_name,omitempty"`
	MatchmakingAddress *microv1.ServiceAddress `json:"matchmaking_address,omitempty"`
	TargetAddress      *microv1.ServiceAddress `json:"target_address,omitempty"` // Game Shard address
	Config             map[string]any          `json:"config,omitempty"`

	// Disconnected parties (tracked during in_game, reported by Game Shard)
	DisconnectedParties []string `json:"disconnected_parties,omitempty"`

	// Capacity
	MinPlayers int `json:"min_players"`
	MaxPlayers int `json:"max_players"`

	// Timestamps
	CreatedAt     time.Time  `json:"created_at"`
	StartedAt     *time.Time `json:"started_at,omitempty"`
	LastHeartbeat *time.Time `json:"last_heartbeat,omitempty"`
}

// HasTeams returns true if the lobby has team assignments.
func (l *Lobby) HasTeams() bool {
	return len(l.Teams) > 0
}

// PartyCount returns the number of parties in the lobby.
func (l *Lobby) PartyCount() int {
	return len(l.Parties)
}

// HasParty returns true if the given party is in the lobby.
func (l *Lobby) HasParty(partyID string) bool {
	for _, p := range l.Parties {
		if p == partyID {
			return true
		}
	}
	return false
}

// IsHost returns true if the given party is the host.
func (l *Lobby) IsHost(partyID string) bool {
	return l.HostPartyID == partyID
}

// GetTeamForParty returns the team name for a given party, or empty string if not found.
func (l *Lobby) GetTeamForParty(partyID string) string {
	for _, team := range l.Teams {
		for _, pid := range team.PartyIDs {
			if pid == partyID {
				return team.Name
			}
		}
	}
	return ""
}

// IsDisconnected returns true if the party is marked as disconnected.
func (l *Lobby) IsDisconnected(partyID string) bool {
	for _, p := range l.DisconnectedParties {
		if p == partyID {
			return true
		}
	}
	return false
}

// CanJoin returns true if the lobby can accept new parties.
func (l *Lobby) CanJoin() bool {
	return l.State == LobbyStateWaiting
}

// CanStart returns true if the lobby can transition to in_game.
func (l *Lobby) CanStart() bool {
	return l.State == LobbyStateReady
}

// CanLeave returns true if parties can leave the lobby.
func (l *Lobby) CanLeave() bool {
	return l.State == LobbyStateWaiting || l.State == LobbyStateReady
}
