/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CardinalServerHandlerTransaction = {
    /**
     * json string
     */
    body?: { [k: string]: any } | undefined;
    hash?: string | undefined;
    namespace?: string | undefined;
    nonce?: number | undefined;
    personaTag?: string | undefined;
    /**
     * hex encoded string
     */
    signature?: string | undefined;
};

/** @internal */
export const CardinalServerHandlerTransaction$inboundSchema: z.ZodType<
    CardinalServerHandlerTransaction,
    z.ZodTypeDef,
    unknown
> = z.object({
    body: z.record(z.any()).optional(),
    hash: z.string().optional(),
    namespace: z.string().optional(),
    nonce: z.number().int().optional(),
    personaTag: z.string().optional(),
    signature: z.string().optional(),
});

/** @internal */
export type CardinalServerHandlerTransaction$Outbound = {
    body?: { [k: string]: any } | undefined;
    hash?: string | undefined;
    namespace?: string | undefined;
    nonce?: number | undefined;
    personaTag?: string | undefined;
    signature?: string | undefined;
};

/** @internal */
export const CardinalServerHandlerTransaction$outboundSchema: z.ZodType<
    CardinalServerHandlerTransaction$Outbound,
    z.ZodTypeDef,
    CardinalServerHandlerTransaction
> = z.object({
    body: z.record(z.any()).optional(),
    hash: z.string().optional(),
    namespace: z.string().optional(),
    nonce: z.number().int().optional(),
    personaTag: z.string().optional(),
    signature: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CardinalServerHandlerTransaction$ {
    /** @deprecated use `CardinalServerHandlerTransaction$inboundSchema` instead. */
    export const inboundSchema = CardinalServerHandlerTransaction$inboundSchema;
    /** @deprecated use `CardinalServerHandlerTransaction$outboundSchema` instead. */
    export const outboundSchema = CardinalServerHandlerTransaction$outboundSchema;
    /** @deprecated use `CardinalServerHandlerTransaction$Outbound` instead. */
    export type Outbound = CardinalServerHandlerTransaction$Outbound;
}
