/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Data = {};

export type PkgWorldDevWorldEngineCardinalTypesEntityStateElement = {
    data?: Data | undefined;
    id?: number | undefined;
};

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z.object({});

/** @internal */
export type Data$Outbound = {};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
    /** @deprecated use `Data$inboundSchema` instead. */
    export const inboundSchema = Data$inboundSchema;
    /** @deprecated use `Data$outboundSchema` instead. */
    export const outboundSchema = Data$outboundSchema;
    /** @deprecated use `Data$Outbound` instead. */
    export type Outbound = Data$Outbound;
}

/** @internal */
export const PkgWorldDevWorldEngineCardinalTypesEntityStateElement$inboundSchema: z.ZodType<
    PkgWorldDevWorldEngineCardinalTypesEntityStateElement,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: z.lazy(() => Data$inboundSchema).optional(),
    id: z.number().int().optional(),
});

/** @internal */
export type PkgWorldDevWorldEngineCardinalTypesEntityStateElement$Outbound = {
    data?: Data$Outbound | undefined;
    id?: number | undefined;
};

/** @internal */
export const PkgWorldDevWorldEngineCardinalTypesEntityStateElement$outboundSchema: z.ZodType<
    PkgWorldDevWorldEngineCardinalTypesEntityStateElement$Outbound,
    z.ZodTypeDef,
    PkgWorldDevWorldEngineCardinalTypesEntityStateElement
> = z.object({
    data: z.lazy(() => Data$outboundSchema).optional(),
    id: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PkgWorldDevWorldEngineCardinalTypesEntityStateElement$ {
    /** @deprecated use `PkgWorldDevWorldEngineCardinalTypesEntityStateElement$inboundSchema` instead. */
    export const inboundSchema =
        PkgWorldDevWorldEngineCardinalTypesEntityStateElement$inboundSchema;
    /** @deprecated use `PkgWorldDevWorldEngineCardinalTypesEntityStateElement$outboundSchema` instead. */
    export const outboundSchema =
        PkgWorldDevWorldEngineCardinalTypesEntityStateElement$outboundSchema;
    /** @deprecated use `PkgWorldDevWorldEngineCardinalTypesEntityStateElement$Outbound` instead. */
    export type Outbound = PkgWorldDevWorldEngineCardinalTypesEntityStateElement$Outbound;
}
