package component

// LobbyState represents the current state of a lobby.
type LobbyState string

const (
	LobbyStateInGame LobbyState = "in_game" // Match active
	LobbyStateEnded  LobbyState = "ended"   // Game finished
)

// LobbySearchFields contains search fields for a player.
type LobbySearchFields struct {
	StringArgs map[string]string `json:"string_args,omitempty"`
	DoubleArgs map[string]any    `json:"double_args,omitempty"`
	Tags       []string          `json:"tags,omitempty"`
}

// LobbyPlayer represents a player in a lobby.
type LobbyPlayer struct {
	PlayerID     string            `json:"player_id"`
	SearchFields LobbySearchFields `json:"search_fields"`
}

// LobbyParty represents a party in a lobby.
type LobbyParty struct {
	PartyID string        `json:"party_id"`
	Players []LobbyPlayer `json:"players"`
}

// LobbyTeam represents a team in a matchmade lobby.
type LobbyTeam struct {
	TeamName string       `json:"team_name"`
	Parties  []LobbyParty `json:"parties"`
}

// LobbyComponent is a container for parties throughout the game lifecycle.
// Created automatically when Match is received from Matchmaking Shard.
// Note: MatchID is the primary key - there is no separate lobby_id.
type LobbyComponent struct {
	// MatchID is the primary identifier for the lobby.
	// This is generated by Matchmaking Shard and used as the lobby key.
	MatchID string `json:"match_id"`

	// Parties is a flat list of party IDs in the lobby.
	Parties []string `json:"parties"`

	// Team assignments from Match
	Teams []LobbyTeam `json:"teams,omitempty"`

	// State is the current lobby state (in_game or ended).
	State LobbyState `json:"state"`

	// MatchProfileName from matchmaking (e.g., "1v1-ranked", "5v5-roles")
	MatchProfileName string `json:"match_profile_name,omitempty"`

	// Game configuration
	Config map[string]string `json:"config,omitempty"`

	// Disconnected players (tracked during in_game, reported by Game Shard)
	DisconnectedPlayers []string `json:"disconnected_players,omitempty"`

	// Timestamps (Unix seconds)
	CreatedAt     int64 `json:"created_at"`
	StartedAt     int64 `json:"started_at,omitempty"`
	LastHeartbeat int64 `json:"last_heartbeat,omitempty"`
}

// Name returns the component name for ECS registration.
func (LobbyComponent) Name() string { return "lobby" }

// HasTeams returns true if the lobby has team assignments.
func (l *LobbyComponent) HasTeams() bool {
	return len(l.Teams) > 0
}

// PartyCount returns the number of parties in the lobby.
func (l *LobbyComponent) PartyCount() int {
	return len(l.Parties)
}

// HasParty returns true if the given party is in the lobby.
func (l *LobbyComponent) HasParty(partyID string) bool {
	for _, p := range l.Parties {
		if p == partyID {
			return true
		}
	}
	return false
}

// GetTeamForParty returns the team name for a given party, or empty string if not found.
func (l *LobbyComponent) GetTeamForParty(partyID string) string {
	for _, team := range l.Teams {
		for _, party := range team.Parties {
			if party.PartyID == partyID {
				return team.TeamName
			}
		}
	}
	return ""
}

// IsPlayerDisconnected returns true if the player is marked as disconnected.
func (l *LobbyComponent) IsPlayerDisconnected(playerID string) bool {
	for _, p := range l.DisconnectedPlayers {
		if p == playerID {
			return true
		}
	}
	return false
}

// MarkPlayerDisconnected marks a player as disconnected.
func (l *LobbyComponent) MarkPlayerDisconnected(playerID string) {
	if !l.IsPlayerDisconnected(playerID) {
		l.DisconnectedPlayers = append(l.DisconnectedPlayers, playerID)
	}
}

// MarkPlayerConnected removes a player from the disconnected list.
func (l *LobbyComponent) MarkPlayerConnected(playerID string) {
	for i, p := range l.DisconnectedPlayers {
		if p == playerID {
			l.DisconnectedPlayers = append(l.DisconnectedPlayers[:i], l.DisconnectedPlayers[i+1:]...)
			return
		}
	}
}
