package component

// LobbyState represents the current state of a lobby.
type LobbyState string

const (
	LobbyStateWaiting LobbyState = "waiting" // Parties gathering, can join/leave
	LobbyStateReady   LobbyState = "ready"   // All parties ready, can start match
	LobbyStateInGame  LobbyState = "in_game" // Match active
	LobbyStateEnded   LobbyState = "ended"   // Game finished
)

// LobbyTeam represents a team in a matchmade lobby.
type LobbyTeam struct {
	TeamName string   `json:"team_name"`
	PartyIDs []string `json:"party_ids"`
}

// LobbyComponent is a container for parties throughout the game lifecycle.
// Created either manually or automatically when Match is received from Matchmaking Shard.
// Note: MatchID is the primary key - there is no separate lobby_id.
type LobbyComponent struct {
	// MatchID is the primary identifier for the lobby.
	// This is generated by Matchmaking Shard and used as the lobby key.
	MatchID string `json:"match_id"`

	HostPartyID string   `json:"host_party_id"`
	Parties     []string `json:"parties"` // Flat list of party IDs

	// Team assignments from Match (only for matchmade lobbies)
	Teams []LobbyTeam `json:"teams,omitempty"`

	State LobbyState `json:"state"`

	// Matchmaking-related fields (set when created from Match)
	MatchProfileName string `json:"match_profile_name,omitempty"`

	// GameShardID for cross-shard game start notification
	GameShardID string `json:"game_shard_id,omitempty"`

	// Game configuration
	Config map[string]string `json:"config,omitempty"`

	// Disconnected parties (tracked during in_game, reported by Game Shard)
	DisconnectedParties []string `json:"disconnected_parties,omitempty"`

	// Capacity
	MinPlayers int `json:"min_players"`
	MaxPlayers int `json:"max_players"`

	// Timestamps (Unix seconds)
	CreatedAt     int64 `json:"created_at"`
	StartedAt     int64 `json:"started_at,omitempty"`
	LastHeartbeat int64 `json:"last_heartbeat,omitempty"`
}

// Name returns the component name for ECS registration.
func (LobbyComponent) Name() string { return "lobby" }

// HasTeams returns true if the lobby has team assignments.
func (l *LobbyComponent) HasTeams() bool {
	return len(l.Teams) > 0
}

// PartyCount returns the number of parties in the lobby.
func (l *LobbyComponent) PartyCount() int {
	return len(l.Parties)
}

// HasParty returns true if the given party is in the lobby.
func (l *LobbyComponent) HasParty(partyID string) bool {
	for _, p := range l.Parties {
		if p == partyID {
			return true
		}
	}
	return false
}

// IsHost returns true if the given party is the host.
func (l *LobbyComponent) IsHost(partyID string) bool {
	return l.HostPartyID == partyID
}

// GetTeamForParty returns the team name for a given party, or empty string if not found.
func (l *LobbyComponent) GetTeamForParty(partyID string) string {
	for _, team := range l.Teams {
		for _, pid := range team.PartyIDs {
			if pid == partyID {
				return team.TeamName
			}
		}
	}
	return ""
}

// IsDisconnected returns true if the party is marked as disconnected.
func (l *LobbyComponent) IsDisconnected(partyID string) bool {
	for _, p := range l.DisconnectedParties {
		if p == partyID {
			return true
		}
	}
	return false
}

// CanJoin returns true if the lobby can accept new parties.
func (l *LobbyComponent) CanJoin() bool {
	return l.State == LobbyStateWaiting
}

// CanStart returns true if the lobby can transition to in_game.
func (l *LobbyComponent) CanStart() bool {
	return l.State == LobbyStateReady
}

// CanLeave returns true if parties can leave the lobby.
func (l *LobbyComponent) CanLeave() bool {
	return l.State == LobbyStateWaiting || l.State == LobbyStateReady
}

// AddParty adds a party to the lobby.
func (l *LobbyComponent) AddParty(partyID string) {
	if !l.HasParty(partyID) {
		l.Parties = append(l.Parties, partyID)
	}
}

// RemoveParty removes a party from the lobby.
func (l *LobbyComponent) RemoveParty(partyID string) {
	for i, p := range l.Parties {
		if p == partyID {
			l.Parties = append(l.Parties[:i], l.Parties[i+1:]...)
			return
		}
	}
}

// MarkDisconnected marks a party as disconnected.
func (l *LobbyComponent) MarkDisconnected(partyID string) {
	if !l.IsDisconnected(partyID) {
		l.DisconnectedParties = append(l.DisconnectedParties, partyID)
	}
}

// MarkConnected removes a party from the disconnected list.
func (l *LobbyComponent) MarkConnected(partyID string) {
	for i, p := range l.DisconnectedParties {
		if p == partyID {
			l.DisconnectedParties = append(l.DisconnectedParties[:i], l.DisconnectedParties[i+1:]...)
			return
		}
	}
}
