// Code generated by world sdk generate. DO NOT EDIT.

//go:build !sdkgen

package component

import (
	component "github.com/argus-labs/world-engine/pkg/template/basic/shards/game/gen/pkg/template/basic/shards/game/component"
	"google.golang.org/protobuf/proto"
)

func (c Gravestone) ToProto() *component.Gravestone {
	p := &component.Gravestone{}
	p.Nickname = string(c.Nickname)
	return p
}

func (c Gravestone) FromProto(p *component.Gravestone) Gravestone {
	if p == nil {
		return c
	}
	c.Nickname = string(p.Nickname)
	return c
}

func (c Gravestone) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal Gravestone: " + err.Error())
	}
	return data
}

func (c Gravestone) UnmarshalWire(data []byte) (any, error) {
	var p component.Gravestone
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c Health) ToProto() *component.Health {
	p := &component.Health{}
	p.HP = int64(c.HP)
	return p
}

func (c Health) FromProto(p *component.Health) Health {
	if p == nil {
		return c
	}
	c.HP = int(p.HP)
	return c
}

func (c Health) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal Health: " + err.Error())
	}
	return data
}

func (c Health) UnmarshalWire(data []byte) (any, error) {
	var p component.Health
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}

func (c PlayerTag) ToProto() *component.PlayerTag {
	p := &component.PlayerTag{}
	p.Nickname = string(c.Nickname)
	return p
}

func (c PlayerTag) FromProto(p *component.PlayerTag) PlayerTag {
	if p == nil {
		return c
	}
	c.Nickname = string(p.Nickname)
	return c
}

func (c PlayerTag) MarshalWire() []byte {
	data, err := proto.Marshal(c.ToProto())
	if err != nil {
		panic("failed to marshal PlayerTag: " + err.Error())
	}
	return data
}

func (c PlayerTag) UnmarshalWire(data []byte) (any, error) {
	var p component.PlayerTag
	if err := proto.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return c.FromProto(&p), nil
}
