// box2d_unity.c — Unity build: compile all vendored Box2D v3 source as a single
// translation unit. CGO compiles .c files in the package directory, so this file
// pulls in every Box2D source file via #include. The result is identical to
// linking a static libbox2d.a, but requires no pre-build step or cmake.

#include "../../third_party/box2d/src/aabb.c"
#include "../../third_party/box2d/src/arena_allocator.c"
#include "../../third_party/box2d/src/array.c"
#include "../../third_party/box2d/src/bitset.c"
#include "../../third_party/box2d/src/body.c"
#include "../../third_party/box2d/src/broad_phase.c"
#include "../../third_party/box2d/src/constraint_graph.c"
#include "../../third_party/box2d/src/contact.c"
#include "../../third_party/box2d/src/contact_solver.c"
#include "../../third_party/box2d/src/core.c"
#include "../../third_party/box2d/src/distance.c"
#include "../../third_party/box2d/src/distance_joint.c"
#include "../../third_party/box2d/src/dynamic_tree.c"
#include "../../third_party/box2d/src/geometry.c"
#include "../../third_party/box2d/src/hull.c"
#include "../../third_party/box2d/src/id_pool.c"
#include "../../third_party/box2d/src/island.c"
#include "../../third_party/box2d/src/joint.c"
#include "../../third_party/box2d/src/manifold.c"
#include "../../third_party/box2d/src/math_functions.c"
#include "../../third_party/box2d/src/motor_joint.c"
#include "../../third_party/box2d/src/mover.c"
#include "../../third_party/box2d/src/physics_world.c"
#include "../../third_party/box2d/src/prismatic_joint.c"
#include "../../third_party/box2d/src/revolute_joint.c"
#include "../../third_party/box2d/src/sensor.c"
#include "../../third_party/box2d/src/shape.c"
#include "../../third_party/box2d/src/solver.c"
#include "../../third_party/box2d/src/solver_set.c"
#include "../../third_party/box2d/src/table.c"
#include "../../third_party/box2d/src/timer.c"
#include "../../third_party/box2d/src/types.c"
#include "../../third_party/box2d/src/weld_joint.c"
#include "../../third_party/box2d/src/wheel_joint.c"
