FROM golang:1.21 AS build

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /usr/src/app

copy . .

RUN go build -gcflags="all=-N -l" -v -o /usr/local/bin/app

FROM ubuntu:22.04
COPY --from=build /go/bin/dlv /usr/local/bin
COPY --from=build /usr/local/bin/app /usr/local/bin/

CMD ["dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/usr/local/bin/app"]
