name: CI

on:
  pull_request:
    paths:
      - docs/**
  push:
    paths:
      - docs/**
    branches:
      - main

jobs:
  lint-docs:
    name: Lint - Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Mintlify CLI
        run: npm install --global mintlify
      - name: Mintlify Check Broken Link
        run: mintlify broken-links
      - name: Mintlify Check Build
        run: |
          timeout --preserve-status --kill-after=10 10s mintlify dev && echo ">> preview build run successfully"
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Preview Instructions
              To preview these changes locally, checkout this branch and run:
              \`\`\`
              make world-docs
              \`\`\``
            })