name: Docs Preview

on:
  pull_request:
    types: [opened]
    paths:
      - docs/**
  push:
    branches:
      - main
jobs:
  mintlify-preview-instructions:
    name: Mintlify Preview Instructions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Preview Instructions
              To preview these changes locally, checkout this branch and run:
              \`\`\`
              make world-docs
              \`\`\``
            })
