name: World Engine - Docs
env:
  VERCEL_ORG_ID: ${{ secrets.DOCS_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.DOCS_VERCEL_PROJECT_ID }}
on:
  pull_request:
    paths:
      - docs/**
    branches:
      - main
      - develop
  push:
    paths:
      - docs/**
    branches:
      - main
jobs:
  deploy-preview:
    if: ${{ github.ref != 'refs/heads/main' }}
    strategy:
      matrix:
        npm-version: [16]
        pnpm-version: [8]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: docs
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.npm-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.DOCS_VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.DOCS_VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: vercel-deploy-results
        run: |
          vercel deploy --prebuilt --token=${{ secrets.DOCS_VERCEL_TOKEN }} 2>&1 | tee output.txt
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "DEPLOY_OUTPUT<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cat output.txt  | grep Inspect)" >> $GITHUB_OUTPUT
          echo "$(cat output.txt  | tail -n 1)" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: Construct PR Comment
        run: |-
          echo "### World Engine Docs deployed (Preview)!" >> PR-COMMENT.txt
          echo "----------------------------------------------" >> PR-COMMENT.txt
          echo "${{ steps.vercel-deploy-results.outputs.DEPLOY_OUTPUT }}" >> PR-COMMENT.txt
          echo "----------------------------------------------" >> PR-COMMENT.txt
      - uses: mshick/add-pr-comment@v2
        with:
          message-path: |
            ./PR-COMMENT.txt
  deploy-production:
#    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        npm-version: [16]
        pnpm-version: [8]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: docs
    permissions:
      pull-requests: write
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.npm-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.DOCS_VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.DOCS_VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: vercel-deploy-results
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.DOCS_VERCEL_TOKEN }} 2>&1 | tee output.txt
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "DEPLOY_OUTPUT<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cat output.txt  | grep Inspect)" >> $GITHUB_OUTPUT
          echo "$(cat output.txt  | grep Production)" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: Construct PR Comment
        run: |-
          echo "### World Engine Docs deployed (Production)!" >> PR-COMMENT.txt
          echo "----------------------------------------------" >> PR-COMMENT.txt
          echo "${{ steps.vercel-deploy-results.outputs.DEPLOY_OUTPUT }}" >> PR-COMMENT.txt
          echo "----------------------------------------------" >> PR-COMMENT.txt
      - uses: mshick/add-pr-comment@v2
        with:
          message-path: |
            ./PR-COMMENT.txt
