name: World Engine - Docs
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    paths:
      - docs/**
    branches:
      - main
      - develop
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: docs
    env:
      VERCEL_ORG_ID: ${{ secrets.DOCS_VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.DOCS_VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.DOCS_VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.DOCS_VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.DOCS_VERCEL_TOKEN }}