name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  md-lint:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      ## detect errors from markdownlint-cli and create annotations for them
      - uses: xt0rted/markdownlint-problem-matcher@v3
      - uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.yaml
          ignore: vendor
          version: 0.39.0
