name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  go-lint:
    name: Go
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.21.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "**/*.sum"
      - name: Make Lint
        run: make lint
