name: Lint

on:
  pull_request:
    types: [opened, synchronized, reopened, ready_for_review]
  push:
    branches:
      - main
jobs:
  Lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.21.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Cache Golang Deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /home/runner/go
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Make Lint
        run: make lint
