name: Lint

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  pr-lint:
    name: PR Title Lint
    permissions:
      pull-requests: read # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write # for amannn/action-semantic-pull-request to mark status of analyzed PR
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.21.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: $GO_VERSION
      - name: Cache Golang Deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /home/runner/go
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Make Lint
        run: make lint
