name: "Nightly E2E run"
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:

  run-tests:
    uses: argus-labs/argus/.github/workflows/test.yml@main

  run-simulations:
    uses: argus-labs/argus/.github/workflows/sims.yml@main
