name: Release

## workflow will trigger on below condition,
## except image release that have jobs condition to trigger only on tagging
on:
  workflow_dispatch:
  push:
    tags:
      - 'evm/v*.*.*'
      - 'relay/nakama/v*.*.*'

env:
  GITHUB_REGISTRY_URL: ghcr.io

jobs:
  evm-release:
    name: EVM Image Release
    if: startsWith(github.ref, 'refs/tags/evm/v')
    runs-on: namespace-profile-linux-8vcpu-16gb-cached
    defaults:
      run:
        shell: bash
        working-directory: evm
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and configure Namespace CLI
        uses: namespacelabs/nscloud-setup@v0
      - name: Configure Namespace powered Buildx
        uses: namespacelabs/nscloud-setup-buildx-action@v0
      - name: Docker - Auth to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Parsing Tag Version
        id: parsed_tag
        run: |
          ## Parse tag name (ex: "refs/tags/v0.0.0 --> v0.0.0)
          ## Or use 'sha_short' when github.ref are main branch (non-tag)

          PARSED_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$PARSED_TAG" == "main" ] && PARSED_TAG=$(git rev-parse --short HEAD)

          echo "tag=$PARSED_TAG" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          IMAGE_NAME: world-engine-nakama
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GITHUB_REGISTRY_URL }}/${{ github.repository_owner }}/world-engine-evm:latest
            ${{ env.GITHUB_REGISTRY_URL }}/${{ github.repository_owner }}/world-engine-evm:${{ env.PARSED_TAG }}

  nakama-release:
    name: Nakama Image Release
    if: startsWith(github.ref, 'refs/tags/relay/nakama/v')
    runs-on: namespace-profile-linux-8vcpu-16gb-cached
    defaults:
      run:
        shell: bash
        working-directory: relay/nakama
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and configure Namespace CLI
        uses: namespacelabs/nscloud-setup@v0
      - name: Configure Namespace powered Buildx
        uses: namespacelabs/nscloud-setup-buildx-action@v0
      - name: Docker - Auth to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Parsing Tag Version
        id: parsed_tag
        run: |
          ## Parse tag name (ex: "refs/tags/v0.0.0 --> v0.0.0)
          ## Or use 'sha_short' when github.ref are main branch (non-tag)

          PARSED_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$PARSED_TAG" == "main" ] && PARSED_TAG=$(git rev-parse --short HEAD)

          echo "tag=$PARSED_TAG" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          IMAGE_NAME: world-engine-nakama
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GITHUB_REGISTRY_URL }}/${{ github.repository_owner }}/world-engine-nakama:latest
            ${{ env.GITHUB_REGISTRY_URL }}/${{ github.repository_owner }}/world-engine-nakama:${{ env.PARSED_TAG }}
