name: Release Nakama

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    uses: ./.github/workflows/templates/docker-build.yaml
    with:
      component: nakama
      dockerfile: ./relay/nakama/Dockerfile
